pipeline {
    agent any
    stages {
        stage('Compile') {
            steps {
                sh "mvnw clean compile"
            }
        }
        stage('Unit-Test') {
            steps {
                sh "mvnw test"
            }
        }
        stage('Integration-Test') {
            steps {
                sh "mvnw test"
            }
        },
        stage('Package') {
            steps {
                sh "mvnw package"
            }
        }
    }
}