pipeline {
    agent any
    stages {
        stage('Compile') {
            steps {
                dir("arith-service"){
                    sh "./mvnw clean compile"
                }
            }
        }
        stage('Unit-Test') {
            steps {
              dir("arith-service"){
                  sh "./mvnw test"
              }
            }
        }
        stage('Integration-Test') {
            steps {
             dir("arith-service"){
                  sh "./mvnw test"
              }
            }
        }
        stage('Package') {
            steps {
                dir("arith-service"){
                    sh "./mvnw package"
                }
            }
        }
        stage('Build image') {
         steps {
            dir("arith-service"){
                dockerImage = docker.build("nagabhushanamn/arith-service:latest")
            }
          }
        }
        stage('Push image') {
            withDockerRegistry([ credentialsId: "docker-hub-credentials", url: "" ]) {
                dockerImage.push()
            }
        }
    }
}