pipeline {
    agent any
    stages {
        stage('Compile') {
            steps {
                dir("arith-service"){
                    sh "./mvnw clean compile"
                }
            }
        }
        stage('Unit-Test') {
            steps {
              dir("arith-service"){
                  sh "./mvnw test"
              }
            }
        }
        stage('Integration-Test') {
            steps {
             dir("arith-service"){
                  sh "./mvnw test"
              }
            }
        }
        stage('Package') {
            steps {
                dir("arith-service"){
                    sh "./mvnw package"
                }
            }
        }
        stage('Build-Docker-Image') {
            steps {
                dir("arith-service"){
                    sh "docker build -t nagabhushanamn/arith-service ."
                }
            }
        }
    }
}